import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from '../src/drizzle/schema';
import { itemLibrary } from '../src/drizzle/schema';

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('DATABASE_URL is not defined in environment variables');
}

const pool = new Pool({ connectionString });
const db = drizzle(pool, { schema });

const items = [
  // ─── LIVING ROOM ───────────────────────────────────────────────────────────
  {
    id: 'lr-sofa-3seat',
    name: 'Sofa (3-Seat)',
    category: 'Seating',
    roomTypes: ['living_room'],
    cuFt: 45,
    weight: 150,
    requiresDisassembly: false,
  },
  {
    id: 'lr-sofa-2seat',
    name: 'Loveseat (2-Seat)',
    category: 'Seating',
    roomTypes: ['living_room'],
    cuFt: 30,
    weight: 100,
  },
  {
    id: 'lr-sofa-sectional',
    name: 'Sectional Sofa',
    category: 'Seating',
    roomTypes: ['living_room'],
    cuFt: 90,
    weight: 250,
    requiresDisassembly: true,
  },
  {
    id: 'lr-armchair',
    name: 'Armchair / Club Chair',
    category: 'Seating',
    roomTypes: ['living_room'],
    cuFt: 20,
    weight: 60,
  },
  {
    id: 'lr-recliner',
    name: 'Recliner Chair',
    category: 'Seating',
    roomTypes: ['living_room'],
    cuFt: 22,
    weight: 80,
  },
  {
    id: 'lr-recliner-electric',
    name: 'Power Recliner (Electric)',
    category: 'Seating',
    roomTypes: ['living_room'],
    cuFt: 24,
    weight: 110,
    isSpecialtyItem: true,
  },
  {
    id: 'lr-ottman',
    name: 'Ottoman / Footstool',
    category: 'Seating',
    roomTypes: ['living_room'],
    cuFt: 8,
    weight: 25,
  },
  {
    id: 'lr-chaise',
    name: 'Chaise Lounge',
    category: 'Seating',
    roomTypes: ['living_room'],
    cuFt: 35,
    weight: 80,
  },
  {
    id: 'lr-coffee-table',
    name: 'Coffee Table',
    category: 'Tables',
    roomTypes: ['living_room'],
    cuFt: 12,
    weight: 40,
    isFragile: true,
  },
  {
    id: 'lr-end-table',
    name: 'End / Side Table',
    category: 'Tables',
    roomTypes: ['living_room'],
    cuFt: 4,
    weight: 20,
  },
  {
    id: 'lr-console-table',
    name: 'Console / Sofa Table',
    category: 'Tables',
    roomTypes: ['living_room'],
    cuFt: 8,
    weight: 30,
  },
  {
    id: 'lr-tv-stand',
    name: 'TV Stand / Media Console',
    category: 'Storage',
    roomTypes: ['living_room'],
    cuFt: 15,
    weight: 60,
  },
  {
    id: 'lr-entertainment-unit',
    name: 'Entertainment Center / Wall Unit',
    category: 'Storage',
    roomTypes: ['living_room'],
    cuFt: 40,
    weight: 150,
    requiresDisassembly: true,
  },
  {
    id: 'lr-bookshelf-sm',
    name: 'Bookshelf (Small)',
    category: 'Storage',
    roomTypes: ['living_room', 'office', 'bedroom'],
    cuFt: 10,
    weight: 35,
  },
  {
    id: 'lr-bookshelf-lg',
    name: 'Bookshelf (Large)',
    category: 'Storage',
    roomTypes: ['living_room', 'office', 'bedroom'],
    cuFt: 20,
    weight: 70,
  },
  {
    id: 'lr-tv-32',
    name: 'TV 32" or Under',
    category: 'Electronics',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 4,
    weight: 15,
    isFragile: true,
  },
  {
    id: 'lr-tv-55',
    name: 'TV 33"–55"',
    category: 'Electronics',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 8,
    weight: 35,
    isFragile: true,
  },
  {
    id: 'lr-tv-65',
    name: 'TV 56"–65"',
    category: 'Electronics',
    roomTypes: ['living_room'],
    cuFt: 12,
    weight: 55,
    isFragile: true,
  },
  {
    id: 'lr-tv-75plus',
    name: 'TV 66"+ (Large)',
    category: 'Electronics',
    roomTypes: ['living_room'],
    cuFt: 18,
    weight: 80,
    isFragile: true,
    isSpecialtyItem: true,
  },
  {
    id: 'lr-floor-lamp',
    name: 'Floor Lamp',
    category: 'Lighting',
    roomTypes: ['living_room', 'bedroom', 'office'],
    cuFt: 3,
    weight: 10,
  },
  {
    id: 'lr-table-lamp',
    name: 'Table Lamp',
    category: 'Lighting',
    roomTypes: ['living_room', 'bedroom', 'office'],
    cuFt: 2,
    weight: 6,
    isFragile: true,
  },
  {
    id: 'lr-area-rug-sm',
    name: 'Area Rug (Small)',
    category: 'Decor',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 4,
    weight: 15,
  },
  {
    id: 'lr-area-rug-lg',
    name: 'Area Rug (Large)',
    category: 'Decor',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 10,
    weight: 40,
  },
  {
    id: 'lr-mirror-wall',
    name: 'Wall Mirror (Large)',
    category: 'Decor',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 8,
    weight: 25,
    isFragile: true,
  },
  {
    id: 'lr-piano-upright',
    name: 'Upright Piano',
    category: 'Specialty',
    roomTypes: ['living_room'],
    cuFt: 45,
    weight: 500,
    isSpecialtyItem: true,
  },
  {
    id: 'lr-piano-grand',
    name: 'Grand Piano',
    category: 'Specialty',
    roomTypes: ['living_room'],
    cuFt: 120,
    weight: 800,
    isSpecialtyItem: true,
  },
  {
    id: 'lr-fireplace-electric',
    name: 'Electric Fireplace',
    category: 'Specialty',
    roomTypes: ['living_room'],
    cuFt: 15,
    weight: 60,
  },

  // ─── BEDROOM ───────────────────────────────────────────────────────────────
  {
    id: 'bd-bed-twin',
    name: 'Twin Bed Frame + Mattress',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 35,
    weight: 80,
  },
  {
    id: 'bd-bed-full',
    name: 'Full/Double Bed Frame + Mattress',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 48,
    weight: 100,
  },
  {
    id: 'bd-bed-queen',
    name: 'Queen Bed Frame + Mattress',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 60,
    weight: 120,
  },
  {
    id: 'bd-bed-king',
    name: 'King Bed Frame + Mattress',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 80,
    weight: 160,
    requiresDisassembly: true,
  },
  {
    id: 'bd-bed-calking',
    name: 'Cal King Bed Frame + Mattress',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 80,
    weight: 170,
    requiresDisassembly: true,
  },
  {
    id: 'bd-bed-adjustable',
    name: 'Adjustable/Smart Bed Base',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 65,
    weight: 200,
    isSpecialtyItem: true,
    requiresDisassembly: true,
  },
  {
    id: 'bd-mattress-only',
    name: 'Mattress Only',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 25,
    weight: 70,
  },
  {
    id: 'bd-headboard',
    name: 'Headboard',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 8,
    weight: 30,
  },
  {
    id: 'bd-dresser',
    name: 'Dresser / Chest of Drawers',
    category: 'Storage',
    roomTypes: ['bedroom'],
    cuFt: 20,
    weight: 80,
  },
  {
    id: 'bd-dresser-tall',
    name: 'Tall Dresser / Tallboy',
    category: 'Storage',
    roomTypes: ['bedroom'],
    cuFt: 15,
    weight: 75,
  },
  {
    id: 'bd-nightstand',
    name: 'Nightstand / Bedside Table',
    category: 'Storage',
    roomTypes: ['bedroom'],
    cuFt: 4,
    weight: 20,
  },
  {
    id: 'bd-wardrobe',
    name: 'Wardrobe / Armoire',
    category: 'Storage',
    roomTypes: ['bedroom'],
    cuFt: 40,
    weight: 150,
    requiresDisassembly: true,
  },
  {
    id: 'bd-wardrobe-walk-in',
    name: 'Walk-in Closet System',
    category: 'Storage',
    roomTypes: ['bedroom'],
    cuFt: 60,
    weight: 200,
    requiresDisassembly: true,
    isSpecialtyItem: true,
  },
  {
    id: 'bd-vanity',
    name: 'Vanity Table + Mirror',
    category: 'Storage',
    roomTypes: ['bedroom'],
    cuFt: 15,
    weight: 50,
    isFragile: true,
  },
  {
    id: 'bd-desk',
    name: 'Desk',
    category: 'Furniture',
    roomTypes: ['bedroom', 'office'],
    cuFt: 15,
    weight: 50,
  },
  {
    id: 'bd-chair-desk',
    name: 'Desk Chair',
    category: 'Seating',
    roomTypes: ['bedroom', 'office'],
    cuFt: 8,
    weight: 25,
  },
  {
    id: 'bd-bench-storage',
    name: 'Storage Bench / Ottoman',
    category: 'Seating',
    roomTypes: ['bedroom'],
    cuFt: 10,
    weight: 30,
  },
  {
    id: 'bd-tv-bedroom',
    name: 'Bedroom TV (Under 55")',
    category: 'Electronics',
    roomTypes: ['bedroom'],
    cuFt: 8,
    weight: 30,
    isFragile: true,
  },
  {
    id: 'bd-safe',
    name: 'Floor Safe / Gun Safe',
    category: 'Specialty',
    roomTypes: ['bedroom', 'office'],
    cuFt: 10,
    weight: 250,
    isSpecialtyItem: true,
    isHighValue: true,
  },
  {
    id: 'bd-baby-crib',
    name: 'Baby Crib / Toddler Bed',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 18,
    weight: 50,
    requiresDisassembly: true,
  },
  {
    id: 'bd-bunk-bed',
    name: 'Bunk Bed',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 50,
    weight: 120,
    requiresDisassembly: true,
  },
  {
    id: 'bd-loft-bed',
    name: 'Loft Bed',
    category: 'Beds',
    roomTypes: ['bedroom'],
    cuFt: 40,
    weight: 100,
    requiresDisassembly: true,
  },

  // ─── KITCHEN ────────────────────────────────────────────────────────────────
  {
    id: 'kt-refrigerator',
    name: 'Refrigerator (Standard)',
    category: 'Appliances',
    roomTypes: ['kitchen'],
    cuFt: 40,
    weight: 200,
    isSpecialtyItem: true,
  },
  {
    id: 'kt-refrigerator-french',
    name: 'Refrigerator (French Door)',
    category: 'Appliances',
    roomTypes: ['kitchen'],
    cuFt: 50,
    weight: 280,
    isSpecialtyItem: true,
  },
  {
    id: 'kt-refrigerator-mini',
    name: 'Mini Fridge',
    category: 'Appliances',
    roomTypes: ['kitchen', 'garage', 'office'],
    cuFt: 8,
    weight: 45,
  },
  {
    id: 'kt-freezer-chest',
    name: 'Chest Freezer',
    category: 'Appliances',
    roomTypes: ['kitchen', 'garage'],
    cuFt: 25,
    weight: 130,
    isSpecialtyItem: true,
  },
  {
    id: 'kt-freezer-upright',
    name: 'Upright Freezer',
    category: 'Appliances',
    roomTypes: ['kitchen', 'garage'],
    cuFt: 25,
    weight: 150,
    isSpecialtyItem: true,
  },
  {
    id: 'kt-stove-gas',
    name: 'Gas Range / Stove',
    category: 'Appliances',
    roomTypes: ['kitchen'],
    cuFt: 22,
    weight: 150,
    isSpecialtyItem: true,
  },
  {
    id: 'kt-stove-electric',
    name: 'Electric Range / Stove',
    category: 'Appliances',
    roomTypes: ['kitchen'],
    cuFt: 22,
    weight: 130,
    isSpecialtyItem: true,
  },
  {
    id: 'kt-microwave-counter',
    name: 'Countertop Microwave',
    category: 'Appliances',
    roomTypes: ['kitchen'],
    cuFt: 3,
    weight: 25,
  },
  {
    id: 'kt-microwave-over',
    name: 'Over-Range Microwave',
    category: 'Appliances',
    roomTypes: ['kitchen'],
    cuFt: 4,
    weight: 30,
  },
  {
    id: 'kt-dishwasher',
    name: 'Dishwasher',
    category: 'Appliances',
    roomTypes: ['kitchen'],
    cuFt: 15,
    weight: 70,
    isSpecialtyItem: true,
  },
  {
    id: 'kt-garbage-disposal',
    name: 'Garbage Disposal',
    category: 'Appliances',
    roomTypes: ['kitchen'],
    cuFt: 1,
    weight: 5,
  },
  {
    id: 'kt-coffee-maker',
    name: 'Coffee Maker / Espresso Machine',
    category: 'Small Appliances',
    roomTypes: ['kitchen'],
    cuFt: 1,
    weight: 5,
  },
  {
    id: 'kt-toaster-oven',
    name: 'Toaster / Toaster Oven',
    category: 'Small Appliances',
    roomTypes: ['kitchen'],
    cuFt: 1,
    weight: 5,
  },
  {
    id: 'kt-blender',
    name: 'Blender / Food Processor',
    category: 'Small Appliances',
    roomTypes: ['kitchen'],
    cuFt: 1,
    weight: 5,
  },
  {
    id: 'kt-air-fryer',
    name: 'Air Fryer / Instant Pot',
    category: 'Small Appliances',
    roomTypes: ['kitchen'],
    cuFt: 1,
    weight: 8,
  },
  {
    id: 'kt-stand-mixer',
    name: 'Stand Mixer (KitchenAid etc.)',
    category: 'Small Appliances',
    roomTypes: ['kitchen'],
    cuFt: 2,
    weight: 25,
  },
  {
    id: 'kt-kitchen-table',
    name: 'Kitchen / Dining Table',
    category: 'Furniture',
    roomTypes: ['kitchen', 'dining_room'],
    cuFt: 20,
    weight: 80,
    requiresDisassembly: true,
  },
  {
    id: 'kt-chairs',
    name: 'Dining Chairs (per chair)',
    category: 'Furniture',
    roomTypes: ['kitchen', 'dining_room'],
    cuFt: 4,
    weight: 15,
  },
  {
    id: 'kt-bar-stool',
    name: 'Bar Stool / Counter Stool',
    category: 'Furniture',
    roomTypes: ['kitchen'],
    cuFt: 3,
    weight: 12,
  },
  {
    id: 'kt-pantry-cabinet',
    name: 'Pantry Cabinet / Food Hutch',
    category: 'Storage',
    roomTypes: ['kitchen'],
    cuFt: 20,
    weight: 75,
  },
  {
    id: 'kt-kitchen-island',
    name: 'Kitchen Island (Freestanding)',
    category: 'Furniture',
    roomTypes: ['kitchen'],
    cuFt: 20,
    weight: 90,
  },
  {
    id: 'kt-wine-cooler',
    name: 'Wine Cooler / Beverage Center',
    category: 'Appliances',
    roomTypes: ['kitchen', 'dining_room'],
    cuFt: 10,
    weight: 60,
    isSpecialtyItem: true,
  },
  {
    id: 'kt-boxes-kitchen',
    name: 'Kitchen Boxes (Packed)',
    category: 'Boxes',
    roomTypes: ['kitchen'],
    cuFt: 5,
    weight: 35,
  },

  // ─── DINING ROOM ────────────────────────────────────────────────────────────
  {
    id: 'dr-dining-table-sm',
    name: 'Dining Table (4-Person)',
    category: 'Furniture',
    roomTypes: ['dining_room'],
    cuFt: 20,
    weight: 75,
    requiresDisassembly: true,
  },
  {
    id: 'dr-dining-table-lg',
    name: 'Dining Table (6–8 Person)',
    category: 'Furniture',
    roomTypes: ['dining_room'],
    cuFt: 32,
    weight: 110,
    requiresDisassembly: true,
  },
  {
    id: 'dr-dining-chair',
    name: 'Dining Chair',
    category: 'Furniture',
    roomTypes: ['dining_room', 'kitchen'],
    cuFt: 4,
    weight: 15,
  },
  {
    id: 'dr-buffet',
    name: 'Buffet / Sideboard',
    category: 'Storage',
    roomTypes: ['dining_room'],
    cuFt: 20,
    weight: 90,
  },
  {
    id: 'dr-hutch',
    name: 'China Hutch / Display Cabinet',
    category: 'Storage',
    roomTypes: ['dining_room'],
    cuFt: 30,
    weight: 120,
    isFragile: true,
    requiresDisassembly: true,
  },
  {
    id: 'dr-bar-cart',
    name: 'Bar Cart',
    category: 'Storage',
    roomTypes: ['dining_room', 'living_room'],
    cuFt: 5,
    weight: 20,
  },
  {
    id: 'dr-chandelier',
    name: 'Chandelier / Pendant Light',
    category: 'Lighting',
    roomTypes: ['dining_room'],
    cuFt: 4,
    weight: 15,
    isFragile: true,
    isSpecialtyItem: true,
  },

  // ─── BATHROOM ───────────────────────────────────────────────────────────────
  {
    id: 'ba-vanity-sink',
    name: 'Bathroom Vanity',
    category: 'Furniture',
    roomTypes: ['bathroom'],
    cuFt: 15,
    weight: 70,
    isSpecialtyItem: true,
  },
  {
    id: 'ba-medicine-cabinet',
    name: 'Medicine Cabinet / Mirror',
    category: 'Storage',
    roomTypes: ['bathroom'],
    cuFt: 3,
    weight: 15,
    isFragile: true,
  },
  {
    id: 'ba-linen-cabinet',
    name: 'Linen Cabinet',
    category: 'Storage',
    roomTypes: ['bathroom'],
    cuFt: 12,
    weight: 45,
  },
  {
    id: 'ba-scale',
    name: 'Bathroom Scale',
    category: 'Small Items',
    roomTypes: ['bathroom'],
    cuFt: 1,
    weight: 3,
  },
  {
    id: 'ba-hamper',
    name: 'Hamper / Laundry Basket',
    category: 'Small Items',
    roomTypes: ['bathroom', 'bedroom'],
    cuFt: 3,
    weight: 5,
  },
  {
    id: 'ba-towel-rack',
    name: 'Towel Rack / Rack Stand',
    category: 'Small Items',
    roomTypes: ['bathroom'],
    cuFt: 2,
    weight: 5,
  },

  // ─── LAUNDRY / UTILITY ──────────────────────────────────────────────────────
  {
    id: 'ul-washer',
    name: 'Washing Machine',
    category: 'Appliances',
    roomTypes: ['basement', 'other'],
    cuFt: 25,
    weight: 200,
    isSpecialtyItem: true,
  },
  {
    id: 'ul-dryer',
    name: 'Dryer',
    category: 'Appliances',
    roomTypes: ['basement', 'other'],
    cuFt: 22,
    weight: 130,
    isSpecialtyItem: true,
  },
  {
    id: 'ul-washer-dryer-combo',
    name: 'Washer/Dryer Combo (Stacked)',
    category: 'Appliances',
    roomTypes: ['basement', 'other'],
    cuFt: 28,
    weight: 250,
    isSpecialtyItem: true,
  },
  {
    id: 'ul-laundry-folding',
    name: 'Folding Table / Utility Table',
    category: 'Furniture',
    roomTypes: ['basement', 'other'],
    cuFt: 8,
    weight: 30,
  },

  // ─── OFFICE ─────────────────────────────────────────────────────────────────
  {
    id: 'of-desk-sm',
    name: 'Small Office Desk',
    category: 'Furniture',
    roomTypes: ['office', 'bedroom'],
    cuFt: 12,
    weight: 40,
  },
  {
    id: 'of-desk-lg',
    name: 'Large Executive Desk',
    category: 'Furniture',
    roomTypes: ['office'],
    cuFt: 25,
    weight: 100,
    requiresDisassembly: true,
  },
  {
    id: 'of-desk-l',
    name: 'L-Shaped Desk',
    category: 'Furniture',
    roomTypes: ['office'],
    cuFt: 30,
    weight: 90,
    requiresDisassembly: true,
  },
  {
    id: 'of-desk-standing',
    name: 'Standing / Adjustable Desk',
    category: 'Furniture',
    roomTypes: ['office'],
    cuFt: 18,
    weight: 80,
    isSpecialtyItem: true,
  },
  {
    id: 'of-chair-office',
    name: 'Office Chair',
    category: 'Seating',
    roomTypes: ['office', 'bedroom'],
    cuFt: 8,
    weight: 30,
  },
  {
    id: 'of-chair-ergonomic',
    name: 'Ergonomic Chair (Herman Miller etc.)',
    category: 'Seating',
    roomTypes: ['office'],
    cuFt: 10,
    weight: 45,
    isHighValue: true,
  },
  {
    id: 'of-filing-cabinet',
    name: 'Filing Cabinet (2-Drawer)',
    category: 'Storage',
    roomTypes: ['office'],
    cuFt: 6,
    weight: 45,
  },
  {
    id: 'of-filing-cabinet-4',
    name: 'Filing Cabinet (4-Drawer)',
    category: 'Storage',
    roomTypes: ['office'],
    cuFt: 12,
    weight: 80,
  },
  {
    id: 'of-monitor',
    name: 'Computer Monitor',
    category: 'Electronics',
    roomTypes: ['office'],
    cuFt: 3,
    weight: 12,
    isFragile: true,
  },
  {
    id: 'of-desktop-pc',
    name: 'Desktop Computer + Tower',
    category: 'Electronics',
    roomTypes: ['office'],
    cuFt: 2,
    weight: 20,
  },
  {
    id: 'of-printer',
    name: 'Printer / Scanner',
    category: 'Electronics',
    roomTypes: ['office'],
    cuFt: 2,
    weight: 15,
  },
  {
    id: 'of-shredder',
    name: 'Shredder',
    category: 'Electronics',
    roomTypes: ['office'],
    cuFt: 2,
    weight: 10,
  },
  {
    id: 'of-whiteboard',
    name: 'Whiteboard',
    category: 'Furniture',
    roomTypes: ['office'],
    cuFt: 6,
    weight: 20,
  },

  // ─── GARAGE / OUTDOOR ───────────────────────────────────────────────────────
  {
    id: 'ga-workbench',
    name: 'Workbench',
    category: 'Furniture',
    roomTypes: ['garage'],
    cuFt: 20,
    weight: 100,
  },
  {
    id: 'ga-toolbox-lg',
    name: 'Tool Chest / Cabinet (Large)',
    category: 'Storage',
    roomTypes: ['garage'],
    cuFt: 20,
    weight: 150,
    isSpecialtyItem: true,
  },
  {
    id: 'ga-toolbox-sm',
    name: 'Portable Toolbox',
    category: 'Storage',
    roomTypes: ['garage'],
    cuFt: 4,
    weight: 30,
  },
  {
    id: 'ga-shelving',
    name: 'Metal Shelving Unit',
    category: 'Storage',
    roomTypes: ['garage', 'basement'],
    cuFt: 15,
    weight: 60,
    requiresDisassembly: true,
  },
  {
    id: 'ga-lawn-mower-push',
    name: 'Push Lawn Mower',
    category: 'Outdoor Equipment',
    roomTypes: ['garage', 'outdoor'],
    cuFt: 8,
    weight: 60,
  },
  {
    id: 'ga-lawn-mower-ride',
    name: 'Riding Lawn Mower',
    category: 'Outdoor Equipment',
    roomTypes: ['garage', 'outdoor'],
    cuFt: 35,
    weight: 400,
    isSpecialtyItem: true,
  },
  {
    id: 'ga-snowblower',
    name: 'Snow Blower',
    category: 'Outdoor Equipment',
    roomTypes: ['garage'],
    cuFt: 12,
    weight: 80,
  },
  {
    id: 'ga-generator',
    name: 'Generator',
    category: 'Outdoor Equipment',
    roomTypes: ['garage'],
    cuFt: 10,
    weight: 100,
    isSpecialtyItem: true,
  },
  {
    id: 'ga-power-tools',
    name: 'Power Tools (Set)',
    category: 'Tools',
    roomTypes: ['garage'],
    cuFt: 5,
    weight: 30,
  },
  {
    id: 'ga-bicycle',
    name: 'Bicycle',
    category: 'Outdoor Equipment',
    roomTypes: ['garage', 'outdoor'],
    cuFt: 8,
    weight: 25,
  },
  {
    id: 'ga-treadmill',
    name: 'Treadmill',
    category: 'Exercise Equipment',
    roomTypes: ['garage', 'basement'],
    cuFt: 30,
    weight: 200,
    isSpecialtyItem: true,
    requiresDisassembly: true,
  },
  {
    id: 'ga-exercise-bike',
    name: 'Exercise Bike / Peloton',
    category: 'Exercise Equipment',
    roomTypes: ['garage', 'bedroom', 'basement'],
    cuFt: 10,
    weight: 70,
    isSpecialtyItem: true,
  },
  {
    id: 'ga-weight-bench',
    name: 'Weight Bench + Weights',
    category: 'Exercise Equipment',
    roomTypes: ['garage', 'basement'],
    cuFt: 15,
    weight: 150,
  },
  {
    id: 'ga-kayak',
    name: 'Kayak / Canoe',
    category: 'Outdoor Equipment',
    roomTypes: ['garage', 'outdoor'],
    cuFt: 40,
    weight: 60,
    isSpecialtyItem: true,
  },
  {
    id: 'ga-bbq-grill',
    name: 'BBQ Grill (Gas)',
    category: 'Outdoor Equipment',
    roomTypes: ['outdoor', 'garage'],
    cuFt: 12,
    weight: 80,
  },
  {
    id: 'ga-bbq-smoker',
    name: 'Smoker / Offset Grill',
    category: 'Outdoor Equipment',
    roomTypes: ['outdoor', 'garage'],
    cuFt: 15,
    weight: 100,
    isSpecialtyItem: true,
  },
  {
    id: 'ga-patio-table',
    name: 'Patio Dining Table',
    category: 'Outdoor Furniture',
    roomTypes: ['outdoor'],
    cuFt: 18,
    weight: 60,
  },
  {
    id: 'ga-patio-chair',
    name: 'Patio Chair (each)',
    category: 'Outdoor Furniture',
    roomTypes: ['outdoor'],
    cuFt: 5,
    weight: 15,
  },
  {
    id: 'ga-patio-couch',
    name: 'Outdoor Sectional / Sofa',
    category: 'Outdoor Furniture',
    roomTypes: ['outdoor'],
    cuFt: 40,
    weight: 80,
  },
  {
    id: 'ga-patio-umbrella',
    name: 'Patio Umbrella + Base',
    category: 'Outdoor Furniture',
    roomTypes: ['outdoor'],
    cuFt: 8,
    weight: 30,
  },
  {
    id: 'ga-fire-pit',
    name: 'Fire Pit',
    category: 'Outdoor Equipment',
    roomTypes: ['outdoor'],
    cuFt: 6,
    weight: 40,
  },
  {
    id: 'ga-kids-playset',
    name: 'Kids Playset / Swing Set',
    category: 'Outdoor Equipment',
    roomTypes: ['outdoor'],
    cuFt: 60,
    weight: 200,
    isSpecialtyItem: true,
    requiresDisassembly: true,
  },
  {
    id: 'ga-hot-tub',
    name: 'Hot Tub / Spa',
    category: 'Specialty',
    roomTypes: ['outdoor', 'garage'],
    cuFt: 120,
    weight: 700,
    isSpecialtyItem: true,
  },
  {
    id: 'ga-pool-table',
    name: 'Pool / Billiard Table',
    category: 'Specialty',
    roomTypes: ['garage', 'basement', 'living_room'],
    cuFt: 60,
    weight: 800,
    isSpecialtyItem: true,
    requiresDisassembly: true,
  },
  {
    id: 'ga-foosball',
    name: 'Foosball / Air Hockey Table',
    category: 'Specialty',
    roomTypes: ['garage', 'basement'],
    cuFt: 15,
    weight: 80,
  },
  {
    id: 'ga-car-motorcycle',
    name: 'Motorcycle',
    category: 'Specialty',
    roomTypes: ['garage'],
    cuFt: 60,
    weight: 500,
    isSpecialtyItem: true,
  },
  {
    id: 'ga-atv',
    name: 'ATV / Golf Cart',
    category: 'Specialty',
    roomTypes: ['garage', 'outdoor'],
    cuFt: 80,
    weight: 600,
    isSpecialtyItem: true,
  },

  // ─── BASEMENT / STORAGE ─────────────────────────────────────────────────────
  {
    id: 'bs-storage-shelves',
    name: 'Storage Shelving System',
    category: 'Storage',
    roomTypes: ['basement', 'storage', 'garage'],
    cuFt: 20,
    weight: 50,
    requiresDisassembly: true,
  },
  {
    id: 'bs-water-heater',
    name: 'Water Heater (Freestanding)',
    category: 'Appliances',
    roomTypes: ['basement'],
    cuFt: 15,
    weight: 130,
    isSpecialtyItem: true,
  },
  {
    id: 'bs-dehumidifier',
    name: 'Dehumidifier',
    category: 'Appliances',
    roomTypes: ['basement'],
    cuFt: 5,
    weight: 30,
  },
  {
    id: 'bs-air-purifier',
    name: 'Air Purifier (Large)',
    category: 'Appliances',
    roomTypes: ['basement', 'bedroom', 'living_room'],
    cuFt: 3,
    weight: 15,
  },
  {
    id: 'bs-sump-pump',
    name: 'Sump Pump',
    category: 'Appliances',
    roomTypes: ['basement'],
    cuFt: 2,
    weight: 15,
  },
  {
    id: 'bs-storage-boxes',
    name: 'Storage Boxes / Totes (each)',
    category: 'Boxes',
    roomTypes: ['basement', 'storage', 'attic'],
    cuFt: 4,
    weight: 30,
  },
  {
    id: 'bs-file-boxes',
    name: 'File Boxes / Bankers Boxes (each)',
    category: 'Boxes',
    roomTypes: ['office', 'basement', 'storage'],
    cuFt: 2,
    weight: 20,
  },
  {
    id: 'bs-wardrobe-box',
    name: 'Wardrobe Box (Hanging Clothes)',
    category: 'Boxes',
    roomTypes: ['bedroom', 'storage'],
    cuFt: 12,
    weight: 25,
  },

  // ─── ART / SPECIALTY ────────────────────────────────────────────────────────
  {
    id: 'sp-art-painting-sm',
    name: 'Painting / Artwork (Small)',
    category: 'Art',
    roomTypes: ['living_room', 'bedroom', 'office'],
    cuFt: 1,
    weight: 5,
    isFragile: true,
    isHighValue: true,
  },
  {
    id: 'sp-art-painting-lg',
    name: 'Painting / Artwork (Large)',
    category: 'Art',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 4,
    weight: 15,
    isFragile: true,
    isHighValue: true,
  },
  {
    id: 'sp-art-sculpture',
    name: 'Sculpture / Statue',
    category: 'Art',
    roomTypes: ['living_room', 'outdoor'],
    cuFt: 4,
    weight: 30,
    isFragile: true,
    isHighValue: true,
    isSpecialtyItem: true,
  },
  {
    id: 'sp-aquarium-sm',
    name: 'Fish Tank (Under 50 Gal)',
    category: 'Specialty',
    roomTypes: ['living_room', 'office'],
    cuFt: 8,
    weight: 60,
    isFragile: true,
    isSpecialtyItem: true,
  },
  {
    id: 'sp-aquarium-lg',
    name: 'Fish Tank (50+ Gal)',
    category: 'Specialty',
    roomTypes: ['living_room'],
    cuFt: 20,
    weight: 150,
    isFragile: true,
    isSpecialtyItem: true,
  },
  {
    id: 'sp-wine-collection',
    name: 'Wine Collection / Cellar Rack',
    category: 'Specialty',
    roomTypes: ['dining_room', 'basement'],
    cuFt: 10,
    weight: 100,
    isFragile: true,
    isHighValue: true,
    isSpecialtyItem: true,
  },

  // ─── BABY / KIDS ────────────────────────────────────────────────────────────
  {
    id: 'kd-changing-table',
    name: 'Changing Table / Dresser',
    category: 'Furniture',
    roomTypes: ['bedroom'],
    cuFt: 12,
    weight: 50,
  },
  {
    id: 'kd-highchair',
    name: 'High Chair',
    category: 'Furniture',
    roomTypes: ['kitchen', 'dining_room'],
    cuFt: 4,
    weight: 15,
  },
  {
    id: 'kd-bouncer-swing',
    name: 'Baby Bouncer / Swing',
    category: 'Baby Gear',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 4,
    weight: 8,
  },
  {
    id: 'kd-playpen',
    name: 'Playpen / Pack-n-Play',
    category: 'Baby Gear',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 6,
    weight: 20,
  },
  {
    id: 'kd-stroller',
    name: 'Stroller / Pram',
    category: 'Baby Gear',
    roomTypes: ['garage', 'other'],
    cuFt: 6,
    weight: 20,
  },
  {
    id: 'kd-kids-bookshelf',
    name: 'Kids Bookshelf / Toy Organizer',
    category: 'Storage',
    roomTypes: ['bedroom'],
    cuFt: 8,
    weight: 25,
  },
  {
    id: 'kd-toy-chest',
    name: 'Toy Chest / Storage Box',
    category: 'Storage',
    roomTypes: ['bedroom', 'living_room'],
    cuFt: 8,
    weight: 20,
  },
  {
    id: 'kd-gaming-setup',
    name: 'Gaming Setup (Console + Accessories)',
    category: 'Electronics',
    roomTypes: ['bedroom', 'living_room'],
    cuFt: 4,
    weight: 20,
    isHighValue: true,
  },

  // ─── MUSICAL INSTRUMENTS ────────────────────────────────────────────────────
  {
    id: 'mi-guitar',
    name: 'Guitar / Bass (with case)',
    category: 'Musical Instruments',
    roomTypes: ['living_room', 'bedroom', 'office'],
    cuFt: 4,
    weight: 10,
    isFragile: true,
  },
  {
    id: 'mi-keyboard',
    name: 'Electronic Keyboard',
    category: 'Musical Instruments',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 12,
    weight: 30,
  },
  {
    id: 'mi-drum-set',
    name: 'Drum Set',
    category: 'Musical Instruments',
    roomTypes: ['living_room', 'garage', 'basement'],
    cuFt: 30,
    weight: 80,
    isSpecialtyItem: true,
    requiresDisassembly: true,
  },
  {
    id: 'mi-speakers',
    name: 'Speakers / Subwoofer (Pair)',
    category: 'Electronics',
    roomTypes: ['living_room', 'bedroom'],
    cuFt: 6,
    weight: 30,
  },

  // ─── ADDITIONAL / MISC ──────────────────────────────────────────────────────
  {
    id: 'ms-ac-window',
    name: 'Window A/C Unit',
    category: 'Appliances',
    roomTypes: ['bedroom', 'living_room'],
    cuFt: 4,
    weight: 40,
  },
  {
    id: 'ms-ac-portable',
    name: 'Portable A/C Unit',
    category: 'Appliances',
    roomTypes: ['bedroom', 'living_room'],
    cuFt: 6,
    weight: 60,
  },
  {
    id: 'ms-space-heater',
    name: 'Space Heater',
    category: 'Appliances',
    roomTypes: ['bedroom', 'office', 'basement'],
    cuFt: 1,
    weight: 5,
  },
  {
    id: 'ms-fan-pedestal',
    name: 'Pedestal / Tower Fan',
    category: 'Appliances',
    roomTypes: ['bedroom', 'living_room'],
    cuFt: 2,
    weight: 10,
  },
  {
    id: 'ms-vacuum',
    name: 'Vacuum Cleaner',
    category: 'Small Appliances',
    roomTypes: ['other'],
    cuFt: 3,
    weight: 15,
  },
  {
    id: 'ms-robot-vacuum',
    name: 'Robot Vacuum (Roomba etc.)',
    category: 'Small Appliances',
    roomTypes: ['other'],
    cuFt: 1,
    weight: 4,
  },
  {
    id: 'ms-ironing-board',
    name: 'Ironing Board + Iron',
    category: 'Small Items',
    roomTypes: ['other'],
    cuFt: 3,
    weight: 8,
  },
  {
    id: 'ms-clothes-rack',
    name: 'Clothes / Garment Rack',
    category: 'Storage',
    roomTypes: ['bedroom', 'other'],
    cuFt: 5,
    weight: 10,
  },
  {
    id: 'ms-ladder',
    name: 'Ladder (6–8 ft)',
    category: 'Tools',
    roomTypes: ['garage', 'other'],
    cuFt: 5,
    weight: 20,
  },
  {
    id: 'ms-plants-large',
    name: 'Large Indoor Plant (Potted)',
    category: 'Decor',
    roomTypes: ['living_room', 'bedroom', 'office'],
    cuFt: 5,
    weight: 30,
  },
  {
    id: 'ms-plants-collection',
    name: 'Plants Collection (10+)',
    category: 'Decor',
    roomTypes: ['living_room', 'outdoor'],
    cuFt: 15,
    weight: 80,
  },
  {
    id: 'ms-litter-box',
    name: 'Cat Tree / Litter Station',
    category: 'Pet Items',
    roomTypes: ['other'],
    cuFt: 8,
    weight: 20,
  },
  {
    id: 'ms-pet-crate',
    name: 'Large Pet Crate / Kennel',
    category: 'Pet Items',
    roomTypes: ['other'],
    cuFt: 8,
    weight: 20,
  },
] satisfies Array<{
  id: string;
  name: string;
  category: string;
  roomTypes: string[];
  cuFt: number;
  weight: number;
  isSpecialtyItem?: boolean;
  requiresDisassembly?: boolean;
  isFragile?: boolean;
  isHighValue?: boolean;
}>;

async function seed() {
  console.log('🌱 Seeding item library...');

  const seedData = items.map((item, idx) => ({
    id: item.id,
    name: item.name,
    category: item.category,
    roomTypes: item.roomTypes,
    cuFt: String(item.cuFt),
    weight: String(item.weight),
    isSpecialtyItem: item.isSpecialtyItem ?? false,
    requiresDisassembly: item.requiresDisassembly ?? false,
    isFragile: item.isFragile ?? false,
    searchKeywords:
      `${item.name} ${item.category} ${item.roomTypes.join(' ')}`.toLowerCase(),
    sortOrder: idx,
    isActive: true,
  }));

  await db
    .insert(itemLibrary)
    .values(seedData)
    .onConflictDoUpdate({
      target: itemLibrary.id,
      set: {
        name: itemLibrary.name,
        category: itemLibrary.category,
        cuFt: itemLibrary.cuFt,
        weight: itemLibrary.weight,
        isActive: itemLibrary.isActive,
      },
    });

  console.log(`✅ Seeded ${seedData.length} items`);

  console.log(`✅ Seeded ${seedData.length} items`);

  // --- ADD THIS PART ---
  console.log('🌱 Creating a test inventory...');

  const testToken = 'test-token-2026-interactive';

  await db.insert(schema.inventories).values({
    token: testToken,
    customerName: 'Seed Test User',
    customerEmail: 'seed@example.com',
    status: 'draft',
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days from now
  }).onConflictDoNothing();

  console.log(`🚀 Test Inventory created! Token: ${testToken}`);
  // ----------------------

  process.exit(0);
}

seed().catch((e) => {
  console.error('Seed error:', e);
  process.exit(1);
});
